/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-17 01:41:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.BoardBean;

public final class qna_005fboard_005fmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.BoardBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	// request 객체에 저장된 BoardBean 객체(article) 가져오기
	BoardBean article = (BoardBean)request.getAttribute("article");
	// request 객체에 저장된 페이지번호(page) 파라미터 가져오기
	String nowPage = request.getParameter("page");

      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>MVC 게시판</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\tmodifyForm {\n");
      out.write("\t\twidth: 500px;\n");
      out.write("\t\theight: 610px;\n");
      out.write("\t\tborder: 1p solid red;\n");
      out.write("\t\tmargin: auto;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\th2 {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\ttable {\n");
      out.write("\t\tmargin: auto;\n");
      out.write("\t\twidth: 450px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.td_left {\n");
      out.write("\t\twidth: 150px;\n");
      out.write("\t\tbackground: orange;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.td_right {\n");
      out.write("\t\twidth: 300px;\n");
      out.write("\t\tbackground: skyblue;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#commandCell {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#board_content {\n");
      out.write("\t\tresize: none;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 게시판 수정하기 -->\n");
      out.write("\t<section id=\"modifyForm\">\n");
      out.write("\t\t<h2>글 수정하기</h2>\n");
      out.write("\t\t<form action=\"BoardModifyPro.bo\" method=\"post\" name=\"modifyForm\">\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"board_num\" value=\"");
      out.print(article.getBoard_num() );
      out.write("\" />\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"page\" value=\"");
      out.print(nowPage );
      out.write("\" />\n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"td_left\"><label for=\"board_name\">글쓴이</label></td>\n");
      out.write("\t\t\t\t\t<td class=\"td_right\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"board_name\" required=\"required\" value=");
      out.print(article.getBoard_name() );
      out.write(" />\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"td_left\"><label for=\"board_pass\">비밀번호</label></td>\n");
      out.write("\t\t\t\t\t<td class=\"td_right\">\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"board_pass\" required=\"required\" />\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"td_left\"><label for=\"board_subject\">제목</label></td>\n");
      out.write("\t\t\t\t\t<td class=\"td_right\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"board_subject\" required=\"required\" value=");
      out.print(article.getBoard_subject() );
      out.write(" />\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"td_left\"><label for=\"board_content\">내용</label></td>\n");
      out.write("\t\t\t\t\t<td class=\"td_right\">\n");
      out.write("\t\t\t\t\t\t<textarea id=\"board_content\" name=\"board_content\" cols=\"40\" rows=\"15\" \n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"required\">");
      out.print(article.getBoard_content() );
      out.write("</textarea>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<section id=\"commandCell\">\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"수정\">&nbsp;&nbsp;\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"뒤로\" onclick=\"history.back()\">\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t</form>\n");
      out.write("\t</section>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
