/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-17 00:18:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.BoardBean;

public final class qna_005fboard_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.BoardBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	// BoardBean 객체 파라미터 가져오기
	BoardBean article = (BoardBean)request.getAttribute("article");

	// page 파라미터 가져오기
	// 1. BoardDetailAction 에서 request.setAttribute() 메서드로 저장했을 경우
// 	String nowPage = (String)request.getAttribute("page");

	// 2. 서블릿 주소로 전달된 page 값을 파라미터 그대로 사용할 경우
	String nowPage = request.getParameter("page");

      out.write("    \n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>MVC 게시판</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\t#articleForm {\n");
      out.write("\t\twidth: 500px;\n");
      out.write("\t\theight: 500px;\n");
      out.write("\t\tborder: 1px solid black;\n");
      out.write("\t\tmargin: auto;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\th2 {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#basicInfoArea {\n");
      out.write("\t\theight: 40px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#articleContentArea {\n");
      out.write("\t\tbackground: orange;\n");
      out.write("\t\tmargin-top: 20px;\n");
      out.write("\t\theight: 350px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\toverflow: auto;\n");
      out.write("\t\twhite-space: pre-line;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#commandList {\n");
      out.write("\t\tmargin: auto;\n");
      out.write("\t\twidth: 500px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 게시판 상세내용 보기 -->\n");
      out.write("\t<section id=\"articleForm\">\n");
      out.write("\t\t<h2>글 상세내용 보기</h2>\n");
      out.write("\t\t<section id=\"basicInfoArea\">\n");
      out.write("\t\t\t제 목 : ");
      out.print(article.getBoard_subject() );
      out.write("<br>\n");
      out.write("\t\t\t첨부파일 : \n");
      out.write("\t\t\t");

				if(article.getBoard_file() != null) {
					
      out.write(" <a href=\"board/file_down.jsp?downFile=");
      out.print(article.getBoard_file());
      out.write('"');
      out.write('>');
      out.print(article.getBoard_file() );
      out.write("</a> ");

				}
			
      out.write("\n");
      out.write("\t\t</section>\n");
      out.write("\t\t<section id=\"articleContentArea\">\n");
      out.write("\t\t\t");
      out.print( article.getBoard_content() );
      out.write("\n");
      out.write("\t\t</section>\n");
      out.write("\t</section>\n");
      out.write("\t<section id=\"commandList\">\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\t\t<input type=\"button\" value=\"답변\" onclick=\"location.href='BoardReplyForm.bo?board_num=");
      out.print(article.getBoard_num());
      out.write("&page=");
      out.print(nowPage);
      out.write("'\">\n");
      out.write("\t\t<input type=\"button\" value=\"수정\" onclick=\"location.href='BoardModifyForm.bo?board_num=");
      out.print(article.getBoard_num());
      out.write("&page=");
      out.print(nowPage);
      out.write("'\">\n");
      out.write("\t\t<input type=\"button\" value=\"삭제\" onclick=\"location.href='BoardDeleteForm.bo?board_num=");
      out.print(article.getBoard_num());
      out.write("&page=");
      out.print(nowPage);
      out.write("'\">\n");
      out.write("\t\t<input type=\"button\" value=\"목록\" onclick=\"location.href='BoardList.bo?page=");
      out.print(nowPage);
      out.write("'\">\n");
      out.write("\t\t&nbsp;&nbsp;\n");
      out.write("\t</section>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
